# Generated by Django 5.1.7 on 2025-04-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
