# Generated by Django 5.1.7 on 2025-04-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload PDF, DOCX, or an image as a certificate.', null=True, upload_to='skill_certificates/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='No Description Provided'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='progress_level',
            field=models.CharField(choices=[('LEARNING', 'Learning'), ('AVERAGE', 'Average'), ('PROGRESS', 'Progressing'), ('DONE', 'Done'), ('EXPERT', 'Expert')], default='LEARNING', max_length=10),
        ),
        migrations.CreateModel(
            name='SkillResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF'), ('DOCX', 'DOCX'), ('VIDEO', 'YouTube Video'), ('LINK', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='skill_resources/')),
                ('link', models.URLField(blank=True, help_text='For external links or YouTube videos.', null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='app_portfolio.skill')),
            ],
        ),
    ]
