# Generated by Django 5.1.7 on 2025-04-01 16:36

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_skill_certificate_skill_description_skill_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.AddField(
            model_name='experience',
            name='contributions',
            field=models.JSONField(default=list, help_text='List of contributions with details such as icon, title, and description.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='detailed_blog',
            field=tinymce.models.HTMLField(default='', help_text='Detailed narrative of the experience with rich text formatting.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills utilized during this experience.', related_name='experiences', to='app_portfolio.skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('current', 'Currently Working'), ('left', 'Left'), ('new', 'Started New')], default='new', help_text='Current status of the job.', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default='No description provided.', help_text='Brief overview of the experience.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the experience. Leave blank if currently working.', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(default='Employee', help_text='Job title or position held.', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(help_text='Start date of the experience.'),
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Images related to the experience.', upload_to='experience_images/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_portfolio.experience')),
            ],
        ),
    ]
